baseURL = "https://www.ifanatic.cn/"
languageCode = "zh-CN"
title = "爱狂热博客"

theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

disqusShortname = "yourdiscussshortname"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "爱狂热"

[params]
  author = "爱狂热"
  subtitle = "专注于PHP、Python、Go语言(golang)、项目管理、软件架构、服务运维"
  keywords = "golang,go语言,PHP,爱狂热,php,python,博客,项目管理,软件架构,公众号,小程序"
  description="技术博客，分享技术方案不限于PHP、Go、Python、前端Vue等语言，包含Linux运维等;项目开发，项目管理，运维部署等方案实施"
  busuanzi = true #启用不算子网页统计
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录

## 友情链接，可以多个

[[params.links]]
  title = "爱狂热的博客"
  name = "爱狂热的博客"
  url = "https://www.ifanatic.cn/"

[[params.links]]
  title = "胡梦旭博客"
  name = "胡梦旭博客"
  url = "http://www.humengxu.com"


## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "https://github.com/hmx224/myHugo.git" ##换成自己得
  issueTerm = "pathname"
  theme = "github-light"


## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 配置网站菜单

[menu]
   [[menu.main]]
      identifier = "go"
      name = "Golang"
      url = "/go/"
      weight =2
  [[menu.main]]
    name       = "分类"
    identifier = "categories"
    url        = "/categories/"
    weight = 3
  [[menu.main]]
    identifier = "php"
    name = "php知识"
    url = "/php/"
    weight = 4
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 5
  [[menu.main]]
      identifier = "interviews"
      name = "面试"
      url = "/interviews/"
      weight =6
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 7


